# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fe30f8f7fd625dc980fcb1d451f56c515359fc0d0e8fc0ce489278e192f4eb8ff2e89d8b1b725b46edfc62b7228ad41ec4ee2e8c2289d5694908aa525c9d0c1b

test:
  secret_key_base: bf2392d3f3568d9adb3a7ac78be4c84bc3db3151922ed347ac00e46d22f7fe4512328519bfd9c6aa5d28a5744730d6d8cd56f24321d9886df0b8525e2373ba0b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
